CLASS zcl_shrinker_demo_1_abap_unit DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS zcl_shrinker_demo_1_abap_unit IMPLEMENTATION.
ENDCLASS.
