*&---------------------------------------------------------------------*
*& Report zshrinker_demo_abap2xlsx_use
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT zshrinker_demo_abap2xlsx_use.

TABLES sscrfields.

INCLUDE zshrinker_demo_abap2xlsx_def.
INCLUDE zshrinker_demo_abap2xlsx_imp.

PARAMETERS p_file TYPE string LOWER CASE DEFAULT 'C:\temp\shrinker_demo_abap2xlsx.xlsx'.

AT SELECTION-SCREEN.
  TRY.
      CASE sscrfields-ucomm.
        WHEN 'ONLI'.
          DATA(lo_excel) = NEW lcl_excel( ).
          DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
          lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = 'Hello this is generated by abap2xlsx via its shrinked version made by https://github.com/sandraros/shrinker' ).
          DATA(lo_writer) = CAST lif_excel_writer( NEW lcl_excel_writer_2007( ) ).
          DATA(xstring) = lo_writer->write_file( lo_excel ).
          DATA(solix_tab) = cl_bcs_convert=>xstring_to_solix( xstring ).
          cl_gui_frontend_services=>gui_download(
            EXPORTING  bin_filesize = xstrlen( xstring )
                       filename     = p_file
                       filetype     = 'BIN'
            CHANGING   data_tab     = solix_tab
            EXCEPTIONS OTHERS       = 24 ).
          IF sy-subrc <> 0.
            MESSAGE ID sy-msgid TYPE sy-msgty NUMBER sy-msgno WITH sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
          ENDIF.
          cl_gui_frontend_services=>execute( document = p_file ).
      ENDCASE.
    CATCH cx_root INTO DATA(lx_root).
      MESSAGE lx_root TYPE 'E'.
  ENDTRY.
